### ISSUE TITLE
do you have relevant pdf or ppt relevant to this repository?

### ISSUE THREAD

**Issue by mrayur** [Justme21/Driving-Simulator#2]
Hi,

Glad to see ur work, I'm doing some researches about game theory and autonomous driving too, may I ask if you have the relevant profiles to help me understand your work. Thanks!

**Comment by henrygouk** [comment]
Hi @mrayur,

There's no paper about this simulator specifically, but we've used it in this paper published at RSS: https://arxiv.org/abs/2009.06394
